# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:
  - npm install

stages:
  - build
  - test

build:server:
  stage: build
  only:
    - master
    - dev
  script:
    - ./node_modules/gulp/bin/gulp.js server:clean
    - ./node_modules/gulp/bin/gulp.js server:ts:build
  artifacts:
    paths:
      - server/

test:server:
  stage: test
  only:
    - master
    - dev
  script:
    - npm run test:restful
  dependencies:
    - build:server